-- Passe D — table cloud_profiles pour synchro multi-appareils
-- À exécuter dans Supabase SQL Editor

create table if not exists public.cloud_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cloud_profiles_user_profile_unique unique (user_id, profile_id)
);

create index if not exists cloud_profiles_user_id_idx on public.cloud_profiles(user_id);
create index if not exists cloud_profiles_profile_id_idx on public.cloud_profiles(profile_id);
create index if not exists cloud_profiles_updated_at_idx on public.cloud_profiles(updated_at desc);

alter table public.cloud_profiles enable row level security;

drop policy if exists "cloud_profiles_select_own" on public.cloud_profiles;
create policy "cloud_profiles_select_own"
on public.cloud_profiles
for select
using (auth.uid() = user_id);

drop policy if exists "cloud_profiles_insert_own" on public.cloud_profiles;
create policy "cloud_profiles_insert_own"
on public.cloud_profiles
for insert
with check (auth.uid() = user_id);

drop policy if exists "cloud_profiles_update_own" on public.cloud_profiles;
create policy "cloud_profiles_update_own"
on public.cloud_profiles
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "cloud_profiles_delete_own" on public.cloud_profiles;
create policy "cloud_profiles_delete_own"
on public.cloud_profiles
for delete
using (auth.uid() = user_id);
